// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2017-08-18 04:45:57.782948492 +0800 +08
// using data from
// https://github.com/golang/go/raw/master/CONTRIBUTORS
package project

var Contributors = []string{
	"Carl Chatfield <carlchatfield@gmail.com>",
	"Carl Henrik Lunde <chlunde@ifi.uio.no>",
	"Carl Jackson <carl@stripe.com>",
	"Carl Johnson <me@carlmjohnson.net>",
	"Carl Mastrangelo <notcarl@google.com>",
	"Carl Shapiro <cshapiro@google.com> <cshapiro@golang.org>",
	"Carlisia Campos <carlisia@grokkingtech.io>",
	"Carlo Alberto Ferraris <cafxx@strayorange.com>",
	"Carlos Castillo <cookieo9@gmail.com>",
	"Carlos Cirello <uldericofilho@gmail.com>",
	"Carlos Eduardo Seo <cseo@linux.vnet.ibm.com>",
	"Dustin Carlino <dcarlino@google.com>",
}
